name: Test and Lint

on:
  push:
    branches: [main, master, dev, staging]
  pull_request:
    branches: [main, master, dev, staging]

jobs:
  validate_terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    container: ronya3data/rony-ci:0.0.1-terraform1.0.3
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod -R +x ./CI/scripts
          ./CI/scripts/validate_terraform.sh
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    container: ronya3data/rony-ci:0.0.1-terraform1.0.3
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod -R +x ./CI/scripts
          ./CI/scripts/test_and_lint.sh
